### ISSUE TITLE
New arxiv scraper isn't being detected

### ISSUE THREAD

**Issue by tfgg** [oakling/akorn.scrapers#6]
Attempting to scrape an arxiv paper yields an exception.

```
>>> s.resolve_scraper('http://arxiv.org/abs/1309.4998')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/akorn.scrapers-0.2._GIT_Unreleased_-py2.7.egg/akorn/scrapers/scrapers.py", line 88, in resolve_scraper
    raise ScraperNotFound("Scraper not found for {}".format(domain))
akorn.scrapers.scrapers.ScraperNotFound: Scraper not found for arxiv.org
```

**Comment by tfgg** [comment]
Great, looks like it was due to arxiv articles not always having a DOI?
